services:
  traefik:
    image: traefik:v2.6
    container_name: local-traefik
    restart: unless-stopped
    networks:
      internal:
    ports:
      - "${IP}:80:80"
      - "${IP}:443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config/dynamic/:/etc/traefik/dynamic/:ro
      - ./traefik/certs:/etc/certs:ro

networks:
  internal:
    external: true
    name: traefik
