http:
  routers:
    local-traefik:
      rule: "Host(`traefik.local`)"
      tls: true
      service: "api@internal"

tls:
  certificates:
    - certFile: "/etc/certs/traefik.local.pem"
      keyFile: "/etc/certs/traefik.local-key.pem"
