http:
  routers:
    local-traefik:
      rule: "Host(`traefik.test`)"
      tls: true
      service: "api@internal"

tls:
  certificates:
    - certFile: "/etc/certs/traefik.test.pem"
      keyFile: "/etc/certs/traefik.test-key.pem"

    - certFile: "/etc/certs/_wildcard.traefik.test.pem"
      keyFile: "/etc/certs/_wildcard.traefik.test-key.pem"
